<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="InnoClinic.Contracts" Version="1.0.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppointmentsAPI.Domain\AppointmentsAPI.Domain.csproj" />
  </ItemGroup>

</Project>
